apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
        volumeMounts:
        - name: my-azuredisk-volume
          mountPath: "/mnt/azure"
        - name: resources
          mountPath: /app/resources
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      volumes:
      - name: my-azuredisk-volume
        persistentVolumeClaim:
          claimName: managed-csi-premium-pvc01
      - name: resources
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80
