apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: kumardeepakdin/nginx-app:1.0
        volumeMounts:
        - name: my-azurefile-volume
          mountPath: "/usr/share/nginx/html/app1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      volumes:
      - name: my-azurefile-volume
        persistentVolumeClaim:
          claimName:  azurefile-csi-premium-pvc01
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80