apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongodb_username: YWRtaW4=
  mongodb_password: cGFzc3dvcmQ=
  mongoexpress_web_username: dXNlcm5hbWU=
  mongoexpress_web_password: cGFzc3dvcmQ=


